DROP TABLE IF EXISTS tblAtividade;
DROP TABLE IF EXISTS tblExercicio;
DROP TABLE IF EXISTS tblMusculo;
DROP TABLE IF EXISTS tblPagamento;
DROP TABLE IF EXISTS tblPlano;
DROP TABLE IF EXISTS tblImc;
DROP TABLE IF EXISTS tblAluno;
DROP TABLE IF EXISTS tblUsuario;
